name: Pipeline

on: [push]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest

    env:
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Cache Batect
        uses: actions/cache@v3.3.2
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache NPM dependencies
        uses: actions/cache@v3.3.2
        with:
          path: .batect/caches
          key: batect-caches-${{ hashFiles('yarn.lock') }}

      - name: Download dependencies
        run: ./batect setup

      - name: Run tests
        run: ./batect e2e
